service_account_key = "BASE64_ENCODED_SERVICE_ACCOUNT_KEY_JSON_JAMA"
project_id         = "glossy-infinity-382611"
region             = "us-central1-c"
account_id         = "Jama-service-account"
display_name       = "Jama-service-account"
role               = "roles/storage.admin"
